version: "3.6"
services:
    nodeserver:
      build:
        context: ./app
      ports:
      - "3000:3000"
      depends_on:
      - mongodb
      - nginx
    nginx:
      build:
        context: ./nginx
      ports:
          - "80:80"
      restart: "always"
    mongodb:
      image : mongo
      container_name: mongodb
      volumes:
        - ./mongodb:/data/db
      ports:
        - 27017:27017
      restart: unless-stopped
